language: node_js
cache: yarn
node_js:
  - "9"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.23.2
  - export PATH="$HOME/.yarn/bin:$PATH"
script: 
- cd dazzling-components && yarn && yarn build
- cd dazzling-core && yarn && yarn test
