language: node_js
# Work-around for https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524.
# (Restore `sudo: false` once that is resolved.)
sudo: required
cache: yarn
node_js:
  - "9"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
script: 
- cd packages/dazzling-components && yarn && yarn build && cd ../..
- cd packages/dazzling-core && yarn && yarn jest
